# Generated by Django 2.2 on 2019-04-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedpoll',
            name='apps_votes',
        ),
        migrations.RemoveField(
            model_name='votedpoll',
            name='fbf_votes',
        ),
        migrations.RemoveField(
            model_name='votedpoll',
            name='health_sciences_votes',
        ),
        migrations.RemoveField(
            model_name='votedpoll',
            name='humanity_votes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=1)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.VotedPoll')),
            ],
        ),
    ]
