# Generated by Django 2.2 on 2019-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190403_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.TextField(default=' '),
        ),
    ]
