# Generated by Django 2.2 on 2019-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
