# Generated by Django 2.2 on 2019-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20190403_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='polls_voted',
            field=models.TextField(default='none'),
        ),
    ]
