# Generated by Django 2.2 on 2019-04-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0008_remove_voter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(default='No gender', max_length=30),
        ),
    ]
