# Generated by Django 2.2 on 2019-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='epe_voted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='it_voted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
