# Generated by Django 2.2 on 2019-04-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20190402_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='epe_voted',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='it_voted',
        ),
    ]
